[build]
builder = "NIXPACKS"
buildCommand = "npm run build:railway"

[deploy]
startCommand = "node .next/standalone/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.build.env]
RAILWAY_STATIC_URL = "https://three-tomorrows-payload-production.up.railway.app"

[environments.production.deploy.env]
RAILWAY_STATIC_URL = "https://three-tomorrows-payload-production.up.railway.app"
NEXT_PUBLIC_SERVER_URL = "https://three-tomorrows-payload-production.up.railway.app"
PAYLOAD_PUBLIC_SERVER_URL = "https://three-tomorrows-payload-production.up.railway.app"